In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv("movies.csv")
credits = pd.read_csv("credits.csv")

In [4]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies = movies.merge(credits,on='title')

In [5]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
#genres
#id
#keywords
#original_title
#overview
#cast 
#crew

movies = movies[['movie_id','original_title','genres','keywords','overview','cast','crew']]

In [7]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
movies.isnull().sum()             #checking the missing data

movie_id          0
original_title    0
genres            0
keywords          0
overview          3
cast              0
crew              0
dtype: int64

In [9]:
movies.dropna()                   #clearing the missing data

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [10]:
movies.duplicated().sum()           #checking the duplicate data

0

In [11]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
import ast                     #used to convert the string of list ot list
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):         #taking only name form the genres
        L.append(i['name'])
    return L

In [13]:
movies['genres'] = movies['genres'].apply(convert)

In [14]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
movies['keywords'] = movies['keywords'].apply(convert)

In [16]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
 def convert3(obj):                #taking the top three actors name of the cast column
    L = []
    counter = 0
    for i in ast.literal_eval(obj):         #taking only name form the cast
        if(counter != 3):
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [18]:
movies['cast'] = movies['cast'].apply(convert3)               ##taking only three values form the cast

In [19]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
def fetch_director(obj):                #taking the top three actors name of the cast column
    L = []
    for i in ast.literal_eval(obj):         #taking only name form the cast
        if(i['job'] == 'Director'):
            L.append(i['name'])
            break;
    return L

In [21]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [22]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [23]:
movies['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4809, dtype: object

In [24]:
movies['overview'] = movies['overview'].astype(str)
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [25]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace (" ","") for i in x])         #removing the spaces to between each ownself for not confusing our model eg - James Cameron to JamesCameron
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace (" ","") for i in x]) 
movies['cast'] = movies['cast'].apply(lambda x:[i.replace (" ","") for i in x]) 
movies['crew'] = movies['crew'].apply(lambda x:[i.replace (" ","") for i in x])

In [27]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [28]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [29]:
movies.head()

,movie_id,original_title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [30]:
new_df = movies[['movie_id','original_title','tags']]

In [31]:
new_df

,movie_id,original_title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [32]:
 new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\atharv gangrade\AppData\Local\Temp\ipykernel_23348\3477895259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [33]:
new_df.head()

,movie_id,original_title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [34]:
 new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\atharv gangrade\AppData\Local\Temp\ipykernel_23348\4280305154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [35]:
new_df.head()

,movie_id,original_title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [36]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\atharv gangrade\appdata\roaming\python\python311\site-packages (1.4.1.post1)
Requirement already satisfied: numpy<2.0,>=1.19.5 in c:\users\atharv gangrade\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.26.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\atharv gangrade\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.12.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\atharv gangrade\appdata\roaming\python\python311\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\atharv gangrade\appdata\roaming\python\python311\site-packages (from scikit-learn) (3.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Program Files\Python311\python.exe -m pip install --upgrade pip

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [61]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [74]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [63]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [67]:
import nltk

In [68]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()                   #by this we are converting the similiar words to the one single word

In [72]:
def stem(text):                    #eg. [love,loving,loved] -> [love,love,love]
    y = []

    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [75]:
new_df['tags'][0]    #see the change below...

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [78]:
stem(new_df['tags'][0])

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [77]:
new_df['tags'] = new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4809, dtype: object

In [79]:
new_df.head()

,movie_id,original_title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [82]:
from sklearn.metrics.pairwise import cosine_similarity

In [84]:
similarity =  cosine_similarity(vectors)                     #it will find angle b/w each movie with each movie to find the nearest movie

In [87]:
similarity[0]

array([0.08980265, 1.        , 0.06350006, ..., 0.02677398, 0.        ,
       0.        ])

In [103]:
new_df[new_df['original_title'] == 'Batman Begins'].index[0]                        #example of finding index

119

In [97]:
sorted(similarity[0],reverse=True)                   #as i m accessing the values by index but after sorting i will lost the index , i will use enumerate function

[1.0000000000000002,
 0.25724787771376323,
 0.2545875386086578,
 0.24948506639458295,
 0.24759378423606915,
 0.24459979523511427,
 0.24056261216234406,
 0.24019223070763068,
 0.23570226039551587,
 0.2311250817605121,
 0.22360679774997894,
 0.22222222222222227,
 0.22075539284417395,
 0.2187974872468418,
 0.2182178902359924,
 0.21629522817435004,
 0.21428571428571427,
 0.21339479988815996,
 0.2132007163556104,
 0.2132007163556104,
 0.2130032168075646,
 0.21300321680756457,
 0.21081851067789195,
 0.21004201260420144,
 0.20953951903123735,
 0.20851441405707477,
 0.20851441405707477,
 0.20309059861498083,
 0.20211302086361077,
 0.20008168266626025,
 0.19999999999999998,
 0.196116135138184,
 0.196116135138184,
 0.19528336647123581,
 0.1924500897298753,
 0.19245008972987526,
 0.19245008972987526,
 0.1911797782254681,
 0.19050019050028574,
 0.1892583246525563,
 0.18898223650461357,
 0.18750000000000003,
 0.18670401120373462,
 0.18633899812498245,
 0.18633899812498245,
 0.18257418583505536,
 0.18220272220337375,
 0.18220272220337375,
 0.18220272220337375,
 0.18220272220337375,
 0.1805787796286538,
 0.1800205749557739,
 0.17766726362967533,
 0.17677669529663687,
 0.17407765595569785,
 0.17391639824998364,
 0.17376201171422898,
 0.17201561551404662,
 0.1714985851425088,
 0.17010345435994292,
 0.16933350266692065,
 0.1690308509457033,
 0.16798421022632318,
 0.16666666666666669,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16666666666666666,
 0.16343011261515333,
 0.16343011261515333,
 0.16037507477489604,
 0.16025399127347054,
 0.16012815380508713,
 0.16012815380508713,
 0.15811388300841897,
 0.15811388300841897,
 0.15748519708717798,
 0.15748519708717798,
 0.15474611514754322,
 0.15430334996209188,
 0.15319083833634298,
 0.15249857033260467,
 0.15214515486254612,
 0.15214515486254612,
 0.15075567228888181,
 0.1496710850223124,
 0.14907119849998599,
 0.14907119849998596,
 0.14907119849998596,
 0.1481668148335556,
 0.1474419561548971,
 0.14731391274719738,
 0.14731391274719738,
 0.14547859349066158,
 0.14547859349066158,
 0.14547859349066158,
 0.14506471329641488,
 0.14433756729740646,
 0.14360673947588817,
 0.14291548761875733,
 0.14291548761875733,
 0.14291548761875733,
 0.14291548761875733,
 0.14213381090374028,
 0.14213381090374028,
 0.14213381090374028,
 0.14213381090374028,
 0.14213381090374028,
 0.14085904245475275,
 0.14002800840280097,
 0.13900960937138318,
 0.1388888888888889,
 0.1388888888888889,
 0.1386750490563073,
 0.1386750490563073,
 0.1386750490563073,
 0.1386750490563073,
 0.13736056394868904,
 0.13699915608779772,
 0.13699915608779772,
 0.13608276348795434,
 0.13608276348795434,
 0.13608276348795434,
 0.13518451760896877,
 0.13518451760896877,
 0.13518451760896877,
 0.13471506281091264,
 0.13382584475782766,
 0.13344012817090595,
 0.13344012817090595,
 0.13333333333333333,
 0.13333333333333333,
 0.13333333333333333,
 0.13333333333333333,
 0.13333333333333333,
 0.13245323570650439,
 0.13176156917368248,
 0.13074409009212268,
 0.13074409009212268,
 0.13074409009212268,
 0.13074409009212268,
 0.13074409009212268,
 0.1301448015738384,
 0.1301448015738384,
 0.12909944487358055,
 0.12909944487358055,
 0.12858612496840993,
 0.12858612496840993,
 0.12858612496840993,
 0.12830005981991682,
 0.12830005981991682,
 0.1270821419438372,
 0.1270821419438372,
 0.1270001270001905,
 0.1259881576697424,
 0.1259881576697424,
 0.1256297269074015,
 0.1256297269074015,
 0.1256297269074015,
 0.125,
 0.12422599874998833,
 0.12422599874998831,
 0.12422599874998831,
 0.12422599874998831,
 0.12403473458920847,
 0.12379689211803457,
 0.12379689211803457,
 0.12379689211803457,
 0.1228682967957476,
 0.1217161238900369,
 0.1217161238900369,
 0.1217161238900369,
 0.1217161238900369,
 0.1217161238900369,
 0.1215541595815788,
 0.1215541595815788,
 0.12126781251816647,
 0.12126781251816647,
 0.12126781251816647,
 0.1203858530857692,
 0.12028130608117205,
 0.11973686801784994,
 0.11904761904761904,
 0.11904761904761904,
 0.11785113019775793,
 0.11785113019775793,
 0.11785113019775792,
 0.11785113019775792,
 0.11785113019775792,
 0.1178511301977579,
 0.1178511301977579,
 0.1178511301977579,
 0.1178511301977579,
 0.1178511301977579,
 0.11669000700233413,
 0.11669000700233413,
 0.1160517706371319,
 0.1160517706371319,
 0.1160517706371319,
 0.1160517706371319,
 0.1160517706371319,
 0.11556254088025605,
 0.11547005383792512,
 0.11470786693528086,
 0.11470786693528086,
 0.11470786693528086,
 0.11470786693528086,
 0.11470786693528086,
 0.11470786693528086,
 0.11433239009500587,
 0.11433239009500587,
 0.11433239009500587,
 0.11433239009500587,
 0.11433239009500587,
 0.11433239009500587,
 0.11340230290662862,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11135885079684349,
 0.11135885079684349,
 0.11135885079684349,
 0.11135885079684349,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.11037769642208699,
 0.11037769642208699,
 0.11037769642208699,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10959932487023819,
 0.10942202738310211,
 0.10942202738310211,
 0.1091089451179962,
 0.1091089451179962,
 0.1091089451179962,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10910894511799618,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10814761408717502,
 0.10675210253672475,
 0.10669739994407998,
 0.10669739994407998,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10660035817780521,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10482848367219183,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10425720702853739,
 0.10411584125907071,
 0.10411584125907071,
 0.10411584125907071,
 0.10411584125907071,
 0.10411584125907071,
 0.10411584125907071,
 0.10314212462587934,
 0.10286889997472794,
 0.10286889997472794,
 0.10286889997472794,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10206207261596575,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10166571355506977,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.1,
 0.09938079899999065,
 0.09889847151615443,
 0.09829463743659808,
 0.09820927516479827,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09805806756909201,
 0.09724332766526303,
 0.09724332766526303,
 0.09622504486493763,
 0.09622504486493763,
 0.09622504486493763,
 0.09622504486493763,
 0.09622504486493763,
 0.09622504486493762,
 0.09622504486493762,
 0.09622504486493762,
 0.09622504486493762,
 0.09622504486493762,
 0.09558988911273406,
 0.09523809523809523,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.0944911182523068,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820634,
 0.09375732507716866,
 0.09335200560186731,
 0.09335200560186731,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09284766908852593,
 0.09259259259259259,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09245003270420485,
 0.09202627172903877,
 0.09157370929912602,
 0.09157370929912602,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09072184232530289,
 0.09072184232530289,
 0.09072184232530289,
 0.09072184232530289,
 0.09072184232530289,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.08980265101338746,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.0890870806374748,
 0.08883363181483767,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08838834764831843,
 0.08830215713766959,
 0.08830215713766959,
 0.08753762190648169,
 0.08753762190648169,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08703882797784893,
 0.08679260732054925,
 0.08679260732054925,
 0.08679260732054925,
 0.08679260732054925,
 0.08679260732054925,
 0.08606629658238703,
 0.08606629658238703,
 0.08606629658238703,
 0.08606629658238703,
 0.08606629658238703,
 0.08606629658238703,
 0.08606629658238703,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08574929257125441,
 0.08535791995526398,
 0.08535791995526398,
 0.08535791995526398,
 0.08535791995526398,
 0.08466675133346033,
 0.08466675133346033,
 0.08466675133346033,
 0.08466675133346033,
 0.08466675133346033,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08399210511316159,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08333333333333333,
 0.08268982305947231,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08219949365267865,
 0.08206099398622181,
 0.08206099398622181,
 0.08144629623753681,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08111071056538127,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08084520834544431,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.08006407690254357,
 0.07909649964604158,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07856742013183862,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07808688094430304,
 0.07749842582921285,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104596,
 0.07715167498104594,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07647191129018724,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07624928516630233,
 0.07597371763975863,
 0.07575757575757576,
 0.07548513560963971,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07537783614444091,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07372097807744857,
 0.07362101738323101,
 0.07293249574894728,
 0.07293249574894728,
 0.07293249574894728,
 0.07293249574894728,
 0.07293249574894728,
 0.07293249574894728,
 0.07293249574894728,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07273929674533079,
 0.07216878364870322,
 0.07216878364870322,
 0.07216878364870322,
 0.07216878364870322,
 0.07142857142857142,
 0.07142857142857142,
 0.07142857142857142,
 0.07142857142857142,
 0.07142857142857142,
 0.07142857142857142,
 0.07142857142857142,
 0.07142857142857142,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07106690545187014,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07068241080666424,
 0.07066652533375734,
 0.07027283689263064,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.07001400420140048,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06950480468569159,
 0.06933752452815364,
 0.06933752452815364,
 0.06933752452815364,
 0.06868028197434452,
 0.06868028197434452,
 0.06868028197434452,
 0.06868028197434452,
 0.06868028197434452,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06804138174397717,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.0674199862463242,
 0.0668153104781061,
 0.0668153104781061,
 0.0668153104781061,
 0.0668153104781061,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06622661785325219,
 0.06622661785325219,
 0.06565321642986127,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06537204504606134,
 0.06509445549041193,
 0.06509445549041193,
 0.06509445549041193,
 0.06509445549041193,
 0.06454972243679027,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06415002990995841,
 0.06401843996644799,
 0.06401843996644799,
 0.06401843996644799,
 0.06401843996644799,
 0.06350006350009524,
 0.06350006350009524,
 0.06350006350009524,
 0.06350006350009524,
 0.06327719971683327,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0629940788348712,
 0.0625,
 0.062017367294604234,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06189844605901729,
 0.06154574548966636,
 0.06154574548966636,
 0.06154574548966636,
 0.06137164119322156,
 0.06108472217815261,
 0.06085806194501845,
 0.06085806194501845,
 0.06085806194501845,
 0.06085806194501845,
 0.06085806194501845,
 0.06085806194501845,

In [99]:
sorted(list(enumerate(similarity[0])),reverse=True)                       #this is sorting the values on the basis of index that i dont want

[(4808, 0.0),
 (4807, 0.027777777777777776),
 (4806, 0.024845199749997663),
 (4805, 0.05270462766947299),
 (4804, 0.02457365935914952),
 (4803, 0.0),
 (4802, 0.057166195047502935),
 (4801, 0.020998026278290397),
 (4800, 0.0),
 (4799, 0.0),
 (4798, 0.0),
 (4797, 0.0),
 (4796, 0.05892556509887895),
 (4795, 0.0),
 (4794, 0.0),
 (4793, 0.0314970394174356),
 (4792, 0.022680460581325723),
 (4791, 0.0),
 (4790, 0.023112508176051212),
 (4789, 0.0),
 (4788, 0.0),
 (4787, 0.0445435403187374),
 (4786, 0.0),
 (4785, 0.026688025634181187),
 (4784, 0.0629940788348712),
 (4783, 0.022680460581325723),
 (4782, 0.0),
 (4781, 0.0),
 (4780, 0.05270462766947299),
 (4779, 0.0),
 (4778, 0.03268602252303067),
 (4777, 0.0),
 (4776, 0.029934217004462485),
 (4775, 0.026028960314767677),
 (4774, 0.04042260417272216),
 (4773, 0.0),
 (4772, 0.0),
 (4771, 0.0),
 (4770, 0.03823595564509362),
 (4769, 0.017972128867239735),
 (4768, 0.0),
 (4767, 0.0),
 (4766, 0.0),
 (4765, 0.0),
 (4764, 0.0314970394174356),
 (4763, 0.0),
 (4762, 0.023809523809523808),
 (4761, 0.0),
 (4760, 0.048112522432468816),
 (4759, 0.0),
 (4758, 0.027399831217559546),
 (4757, 0.0314970394174356),
 (4756, 0.0),
 (4755, 0.029934217004462485),
 (4754, 0.0),
 (4753, 0.0),
 (4752, 0.0),
 (4751, 0.025125945381480302),
 (4750, 0.0),
 (4749, 0.0),
 (4748, 0.0),
 (4747, 0.03268602252303067),
 (4746, 0.017666631333439334),
 (4745, 0.0445435403187374),
 (4744, 0.036369648372665396),
 (4743, 0.0),
 (4742, 0.027399831217559546),
 (4741, 0.0),
 (4740, 0.0890870806374748),
 (4739, 0.0),
 (4738, 0.0),
 (4737, 0.0),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.029934217004462485),
 (4733, 0.025125945381480302),
 (4732, 0.0),
 (4731, 0.0),
 (4730, 0.06666666666666667),
 (4729, 0.0),
 (4728, 0.0),
 (4727, 0.0),
 (4726, 0.0),
 (4725, 0.019641855032959656),
 (4724, 0.0),
 (4723, 0.030949223029508643),
 (4722, 0.0),
 (4721, 0.08606629658238703),
 (4720, 0.0),
 (4719, 0.0),
 (4718, 0.0),
 (4717, 0.0),
 (4716, 0.026028960314767677),
 (4715, 0.0),
 (4714, 0.0200643088476282),
 (4713, 0.0),
 (4712, 0.0),
 (4711, 0.0),
 (4710, 0.02817180849095055),
 (4709, 0.012745318548364542),
 (4708, 0.0),
 (4707, 0.06537204504606134),
 (4706, 0.036369648372665396),
 (4705, 0.0),
 (4704, 0.0),
 (4703, 0.036369648372665396),
 (4702, 0.032075014954979206),
 (4701, 0.0),
 (4700, 0.0),
 (4699, 0.017282528245507085),
 (4698, 0.022680460581325723),
 (4697, 0.023809523809523808),
 (4696, 0.029934217004462485),
 (4695, 0.0),
 (4694, 0.029934217004462485),
 (4693, 0.025416428388767443),
 (4692, 0.0),
 (4691, 0.0),
 (4690, 0.0),
 (4689, 0.0),
 (4688, 0.0),
 (4687, 0.0),
 (4686, 0.0),
 (4685, 0.018184824186332698),
 (4684, 0.0),
 (4683, 0.032075014954979206),
 (4682, 0.0),
 (4681, 0.0),
 (4680, 0.0),
 (4679, 0.0),
 (4678, 0.029012942659282975),
 (4677, 0.02817180849095055),
 (4676, 0.1259881576697424),
 (4675, 0.049690399499995326),
 (4674, 0.0),
 (4673, 0.020833333333333332),
 (4672, 0.029934217004462485),
 (4671, 0.0),
 (4670, 0.03268602252303067),
 (4669, 0.034020690871988585),
 (4668, 0.0),
 (4667, 0.0314970394174356),
 (4666, 0.0),
 (4665, 0.0),
 (4664, 0.032075014954979206),
 (4663, 0.0),
 (4662, 0.0),
 (4661, 0.0),
 (4660, 0.08838834764831843),
 (4659, 0.022473328748774737),
 (4658, 0.0),
 (4657, 0.0890870806374748),
 (4656, 0.0),
 (4655, 0.034020690871988585),
 (4654, 0.0),
 (4653, 0.0),
 (4652, 0.0),
 (4651, 0.0),
 (4650, 0.0222717701593687),
 (4649, 0.0445435403187374),
 (4648, 0.0),
 (4647, 0.0),
 (4646, 0.046225016352102424),
 (4645, 0.036369648372665396),
 (4644, 0.08333333333333333),
 (4643, 0.07905694150420949),
 (4642, 0.0),
 (4641, 0.07106690545187014),
 (4640, 0.0),
 (4639, 0.05892556509887895),
 (4638, 0.043033148291193514),
 (4637, 0.027399831217559546),
 (4636, 0.026352313834736494),
 (4635, 0.036369648372665396),
 (4634, 0.0),
 (4633, 0.018633899812498245),
 (4632, 0.030949223029508643),
 (4631, 0.0),
 (4630, 0.0),
 (4629, 0.09128709291752768),
 (4628, 0.0),
 (4627, 0.05270462766947299),
 (4626, 0.10660035817780521),
 (4625, 0.0),
 (4624, 0.0),
 (4623, 0.025717224993681984),
 (4622, 0.0),
 (4621, 0.032075014954979206),
 (4620, 0.0),
 (4619, 0.0),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.036369648372665396),
 (4613, 0.0),
 (4612, 0.0),
 (4611, 0.0),
 (4610, 0.042333375666730164),
 (4609, 0.0),
 (4608, 0.0),
 (4607, 0.03823595564509362),
 (4606, 0.0),
 (4605, 0.05555555555555555),
 (4604, 0.0),
 (4603, 0.0),
 (4602, 0.0),
 (4601, 0.0),
 (4600, 0.050251890762960605),
 (4599, 0.05270462766947299),
 (4598, 0.0),
 (4597, 0.041666666666666664),
 (4596, 0.0),
 (4595, 0.0),
 (4594, 0.06804138174397717),
 (4593, 0.024845199749997663),
 (4592, 0.029012942659282975),
 (4591, 0.0),
 (4590, 0.046225016352102424),
 (4589, 0.0),
 (4588, 0.0),
 (4587, 0.0),
 (4586, 0.0),
 (4585, 0.038749212914606423),
 (4584, 0.0),
 (4583, 0.0),
 (4582, 0.0),
 (4581, 0.0),
 (4580, 0.0),
 (4579, 0.026028960314767677),
 (4578, 0.030949223029508643),
 (4577, 0.0),
 (4576, 0.041666666666666664),
 (4575, 0.0),
 (4574, 0.0),
 (4573, 0.03268602252303067),
 (4572, 0.029934217004462485),
 (4571, 0.08084520834544431),
 (4570, 0.0),
 (4569, 0.06537204504606134),
 (4568, 0.015541746804005229),
 (4567, 0.0445435403187374),
 (4566, 0.0),
 (4565, 0.0),
 (4564, 0.0),
 (4563, 0.06415002990995841),
 (4562, 0.043396303660274624),
 (4561, 0.027036903521793755),
 (4560, 0.03928371006591931),
 (4559, 0.0),
 (4558, 0.0445435403187374),
 (4557, 0.03823595564509362),
 (4556, 0.027399831217559546),
 (4555, 0.024310831916315757),
 (4554, 0.0),
 (4553, 0.0),
 (4552, 0.030949223029508643),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.0),
 (4548, 0.10669739994407998),
 (4547, 0.0),
 (4546, 0.029012942659282975),
 (4545, 0.0445435403187374),
 (4544, 0.0),
 (4543, 0.029462782549439476),
 (4542, 0.0),
 (4541, 0.07001400420140048),
 (4540, 0.0),
 (4539, 0.030429030972509225),
 (4538, 0.03726779962499649),
 (4537, 0.0),
 (4536, 0.05555555555555555),
 (4535, 0.018633899812498245),
 (4534, 0.0),
 (4533, 0.024845199749997663),
 (4532, 0.024056261216234408),
 (4531, 0.050251890762960605),
 (4530, 0.0),
 (4529, 0.0),
 (4528, 0.021884405476620423),
 (4527, 0.0),
 (4526, 0.0),
 (4525, 0.0),
 (4524, 0.0),
 (4523, 0.0),
 (4522, 0.05986843400892497),
 (4521, 0.0),
 (4520, 0.0),
 (4519, 0.09245003270420485),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.0),
 (4515, 0.04914731871829904),
 (4514, 0.0),
 (4513, 0.029012942659282975),
 (4512, 0.0),
 (4511, 0.0),
 (4510, 0.0),
 (4509, 0.021698151830137312),
 (4508, 0.0),
 (4507, 0.0),
 (4506, 0.0),
 (4505, 0.09245003270420485),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.0),
 (4501, 0.02817180849095055),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.0),
 (4497, 0.0),
 (4496, 0.0),
 (4495, 0.08606629658238703),
 (4494, 0.0),
 (4493, 0.13608276348795434),
 (4492, 0.0),
 (4491, 0.0),
 (4490, 0.0),
 (4489, 0.0),
 (4488, 0.034020690871988585),
 (4487, 0.02457365935914952),
 (4486, 0.0),
 (4485, 0.03268602252303067),
 (4484, 0.0),
 (4483, 0.0),
 (4482, 0.0),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.0),
 (4476, 0.08333333333333333),
 (4475, 0.07106690545187014),
 (4474, 0.0),
 (4473, 0.0),
 (4472, 0.026352313834736494),
 (4471, 0.09284766908852593),
 (4470, 0.0),
 (4469, 0.020998026278290397),
 (4468, 0.0),
 (4467, 0.0),
 (4466, 0.03928371006591931),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.04042260417272216),
 (4462, 0.032075014954979206),
 (4461, 0.026688025634181187),
 (4460, 0.0),
 (4459, 0.0),
 (4458, 0.0),
 (4457, 0.0),
 (4456, 0.05270462766947299),
 (4455, 0.0),
 (4454, 0.08111071056538127),
 (4453, 0.026688025634181187),
 (4452, 0.0),
 (4451, 0.0),
 (4450, 0.0),
 (4449, 0.026352313834736494),
 (4448, 0.0),
 (4447, 0.0),
 (4446, 0.07453559924999298),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.0),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0),
 (4437, 0.0),
 (4436, 0.03268602252303067),
 (4435, 0.0),
 (4434, 0.0),
 (4433, 0.08333333333333333),
 (4432, 0.0),
 (4431, 0.041996052556580794),
 (4430, 0.0),
 (4429, 0.025416428388767443),
 (4428, 0.0),
 (4427, 0.0),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.02817180849095055),
 (4423, 0.034752402342845795),
 (4422, 0.029462782549439476),
 (4421, 0.0),
 (4420, 0.0),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.030429030972509225),
 (4414, 0.07856742013183862),
 (4413, 0.0),
 (4412, 0.02817180849095055),
 (4411, 0.0),
 (4410, 0.034020690871988585),
 (4409, 0.0),
 (4408, 0.029462782549439476),
 (4407, 0.19245008972987526),
 (4406, 0.0),
 (4405, 0.07453559924999298),
 (4404, 0.032075014954979206),
 (4403, 0.026352313834736494),
 (4402, 0.03928371006591931),
 (4401, 0.048621663832631515),
 (4400, 0.0),
 (4399, 0.022473328748774737),
 (4398, 0.0),
 (4397, 0.0),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.025125945381480302),
 (4393, 0.0),
 (4392, 0.04042260417272216),
 (4391, 0.0),
 (4390, 0.018633899812498245),
 (4389, 0.0),
 (4388, 0.0),
 (4387, 0.0),
 (4386, 0.046676002800933654),
 (4385, 0.026688025634181187),
 (4384, 0.05143444998736397),
 (4383, 0.0),
 (4382, 0.027777777777777776),
 (4381, 0.0),
 (4380, 0.0),
 (4379, 0.057166195047502935),
 (4378, 0.0),
 (4377, 0.048112522432468816),
 (4376, 0.0),
 (4375, 0.0),
 (4374, 0.027036903521793755),
 (4373, 0.025416428388767443),
 (4372, 0.0),
 (4371, 0.053376051268362375),
 (4370, 0.04042260417272216),
 (4369, 0.0),
 (4368, 0.0),
 (4367, 0.043033148291193514),
 (4366, 0.0),
 (4365, 0.0),
 (4364, 0.0445435403187374),
 (4363, 0.0),
 (4362, 0.0),
 (4361, 0.023809523809523808),
 (4360, 0.023570226039551584),
 (4359, 0.06804138174397717),
 (4358, 0.0),
 (4357, 0.06666666666666667),
 (4356, 0.0),
 (4355, 0.09245003270420485),
 (4354, 0.0),
 (4353, 0.03726779962499649),
 (4352, 0.0),
 (4351, 0.0314970394174356),
 (4350, 0.1386750490563073),
 (4349, 0.0),
 (4348, 0.0),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.07293249574894728),
 (4344, 0.0),
 (4343, 0.029012942659282975),
 (4342, 0.0),
 (4341, 0.05986843400892497),
 (4340, 0.0),
 (4339, 0.0),
 (4338, 0.15811388300841897),
 (4337, 0.027036903521793755),
 (4336, 0.0),
 (4335, 0.048112522432468816),
 (4334, 0.04042260417272216),
 (4333, 0.10425720702853739),
 (4332, 0.041344911529736156),
 (4331, 0.0563436169819011),
 (4330, 0.0),
 (4329, 0.030949223029508643),
 (4328, 0.0),
 (4327, 0.02457365935914952),
 (4326, 0.03553345272593507),
 (4325, 0.0),
 (4324, 0.0),
 (4323, 0.0),
 (4322, 0.06950480468569159),
 (4321, 0.034380708208626445),
 (4320, 0.0),
 (4319, 0.026688025634181187),
 (4318, 0.05802588531856595),
 (4317, 0.0),
 (4316, 0.03928371006591931),
 (4315, 0.034020690871988585),
 (4314, 0.06537204504606134),
 (4313, 0.0),
 (4312, 0.0),
 (4311, 0.0),
 (4310, 0.0),
 (4309, 0.0),
 (4308, 0.0),
 (4307, 0.06154574548966636),
 (4306, 0.0),
 (4305, 0.0),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.04042260417272216),
 (4301, 0.026688025634181187),
 (4300, 0.0),
 (4299, 0.0),
 (4298, 0.0),
 (4297, 0.0),
 (4296, 0.0),
 (4295, 0.05555555555555555),
 (4294, 0.03333333333333333),
 (4293, 0.0),
 (4292, 0.07106690545187014),
 (4291, 0.0),
 (4290, 0.026688025634181187),
 (4289, 0.0),
 (4288, 0.0),
 (4287, 0.0),
 (4286, 0.026352313834736494),
 (4285, 0.0),
 (4284, 0.034020690871988585),
 (4283, 0.05270462766947299),
 (4282, 0.023570226039551584),
 (4281, 0.048112522432468816),
 (4280, 0.0),
 (4279, 0.01924500897298752),
 (4278, 0.0),
 (4277, 0.0),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.0),
 (4270, 0.026028960314767677),
 (4269, 0.022893427324781505),
 (4268, 0.0),
 (4267, 0.027036903521793755),
 (4266, 0.026028960314767677),
 (4265, 0.026352313834736494),
 (4264, 0.0),
 (4263, 0.046225016352102424),
 (4262, 0.0),
 (4261, 0.08838834764831843),
 (4260, 0.0),
 (4259, 0.0),
 (4258, 0.10206207261596575),
 (4257, 0.0),
 (4256, 0.0),
 (4255, 0.0),
 (4254, 0.018294043331615058),
 (4253, 0.0),
 (4252, 0.029012942659282975),
 (4251, 0.0222717701593687),
 (4250, 0.04042260417272216),
 (4249, 0.0),
 (4248, 0.05270462766947299),
 (4247, 0.0),
 (4246, 0.0),
 (4245, 0.043033148291193514),
 (4244, 0.0),
 (4243, 0.0),
 (4242, 0.029462782549439476),
 (4241, 0.0),
 (4240, 0.027777777777777776),
 (4239, 0.022473328748774737),
 (4238, 0.0),
 (4237, 0.018751465015433733),
 (4236, 0.0314970394174356),
 (4235, 0.0),
 (4234, 0.0),
 (4233, 0.0),
 (4232, 0.10814761408717502),
 (4231, 0.0),
 (4230, 0.03553345272593507),
 (4229, 0.0),
 (4228, 0.0),
 (4227, 0.0167506302543202),
 (4226, 0.0),
 (4225, 0.0),
 (4224, 0.0),
 (4223, 0.0),
 (4222, 0.03553345272593507),
 (4221, 0.0),
 (4220, 0.0),
 (4219, 0.0),
 (4218, 0.06804138174397717),
 (4217, 0.027036903521793755),
 (4216, 0.0),
 (4215, 0.028583097523751468),
 (4214, 0.0),
 (4213, 0.029934217004462485),
 (4212, 0.0),
 (4211, 0.02817180849095055),
 (4210, 0.0),
 (4209, 0.0),
 (4208, 0.03928371006591931),
 (4207, 0.05555555555555555),
 (4206, 0.03553345272593507),
 (4205, 0.125),
 (4204, 0.03333333333333333),
 (4203, 0.0),
 (4202, 0.0),
 (4201, 0.0),
 (4200, 0.10660035817780521),
 (4199, 0.0),
 (4198, 0.06537204504606134),
 (4197, 0.036369648372665396),
 (4196, 0.025125945381480302),
 (4195, 0.034020690871988585),
 (4194, 0.2132007163556104),
 (4193, 0.0),
 (4192, 0.0),
 (4191, 0.0),
 (4190, 0.0),
 (4189, 0.027777777777777776),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.034020690871988585),
 (4185, 0.0),
 (4184, 0.0),
 (4183, 0.07071067811865475),
 (4182, 0.04914731871829904),
 (4181, 0.024310831916315757),
 (4180, 0.0),
 (4179, 0.0),
 (4178, 0.0),
 (4177, 0.0),
 (4176, 0.0),
 (4175, 0.0),
 (4174, 0.0),
 (4173, 0.0),
 (4172, 0.0),
 (4171, 0.021339479988815996),
 (4170, 0.029462782549439476),
 (4169, 0.0),
 (4168, 0.032075014954979206),
 (4167, 0.08606629658238703),
 (4166, 0.0),
 (4165, 0.0),
 (4164, 0.0),
 (4163, 0.018993429409939658),
 (4162, 0.047619047619047616),
 (4161, 0.0),
 (4160, 0.0),
 (4159, 0.0),
 (4158, 0.0),
 (4157, 0.0),
 (4156, 0.04578685464956301),
 (4155, 0.0),
 (4154, 0.0),
 (4153, 0.02797271194322297),
 (4152, 0.0),
 (4151, 0.0),
 (4150, 0.0629940788348712),
 (4149, 0.0),
 (4148, 0.0),
 (4147, 0.0),
 (4146, 0.0),
 (4145, 0.0),
 (4144, 0.0),
 (4143, 0.0),
 (4142, 0.03268602252303067),
 (4141, 0.0),
 (4140, 0.0),
 (4139, 0.0200643088476282),
 (4138, 0.03823595564509362),
 (4137, 0.0),
 (4136, 0.11180339887498947),
 (4135, 0.06415002990995841),
 (4134, 0.0),
 (4133, 0.03823595564509362),
 (4132, 0.041666666666666664),
 (4131, 0.03928371006591931),
 (4130, 0.017099639201419235),
 (4129, 0.0),
 (4128, 0.026688025634181187),
 (4127, 0.0),
 (4126, 0.0563436169819011),
 (4125, 0.0),
 (4124, 0.07715167498104596),
 (4123, 0.0),
 (4122, 0.0),
 (4121, 0.06622661785325219),
 (4120, 0.0314970394174356),
 (4119, 0.0),
 (4118, 0.022075539284417398),
 (4117, 0.017190354104313223),
 (4116, 0.0),
 (4115, 0.030949223029508643),
 (4114, 0.030429030972509225),
 (4113, 0.03268602252303067),
 (4112, 0.0),
 (4111, 0.0),
 (4110, 0.028583097523751468),
 (4109, 0.0),
 (4108, 0.03333333333333333),
 (4107, 0.0),
 (4106, 0.02457365935914952),
 (4105, 0.0),
 (4104, 0.049690399499995326),
 (4103, 0.0),
 (4102, 0.0),
 (4101, 0.021698151830137312),
 (4100, 0.07453559924999298),
 (4099, 0.0),
 (4098, 0.1111111111111111),
 (4097, 0.0),
 (4096, 0.0),
 (4095, 0.034752402342845795),
 (4094, 0.0),
 (4093, 0.0),
 (4092, 0.0314970394174356),
 (4091, 0.06804138174397717),
 (4090, 0.0),
 (4089, 0.0),
 (4088, 0.0),
 (4087, 0.0),
 (4086, 0.032075014954979206),
 (4085, 0.05479966243511909),
 (4084, 0.07905694150420949),
 (4083, 0.0),
 (4082, 0.0),
 (4081, 0.026028960314767677),
 (4080, 0.10959932487023819),
 (4079, 0.028583097523751468),
 (4078, 0.043033148291193514),
 (4077, 0.04042260417272216),
 (4076, 0.046225016352102424),
 (4075, 0.0),
 (4074, 0.0),
 (4073, 0.0),
 (4072, 0.0),
 (4071, 0.0),
 (4070, 0.0),
 (4069, 0.02457365935914952),
 (4068, 0.025125945381480302),
 (4067, 0.036369648372665396),
 (4066, 0.030949223029508643),
 (4065, 0.0),
 (4064, 0.050251890762960605),
 (4063, 0.048112522432468816),
 (4062, 0.08333333333333333),
 (4061, 0.0),
 (4060, 0.0),
 (4059, 0.0),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.08111071056538127),
 (4055, 0.0),
 (4054, 0.0),
 (4053, 0.050251890762960605),
 (4052, 0.021698151830137312),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.19528336647123581),
 (4048, 0.0),
 (4047, 0.0),
 (4046, 0.10286889997472794),
 (4045, 0.041666666666666664),
 (4044, 0.0),
 (4043, 0.0),
 (4042, 0.0),
 (4041, 0.0),
 (4040, 0.029462782549439476),
 (4039, 0.06666666666666667),
 (4038, 0.029462782549439476),
 (4037, 0.046225016352102424),
 (4036, 0.0),
 (4035, 0.0),
 (4034, 0.0),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.03726779962499649),
 (4030, 0.036369648372665396),
 (4029, 0.01950685786602176),
 (4028, 0.0),
 (4027, 0.041666666666666664),
 (4026, 0.036369648372665396),
 (4025, 0.0),
 (4024, 0.032075014954979206),
 (4023, 0.027036903521793755),
 (4022, 0.022680460581325723),
 (4021, 0.0),
 (4020, 0.032075014954979206),
 (4019, 0.11180339887498947),
 (4018, 0.022075539284417398),
 (4017, 0.0),
 (4016, 0.0),
 (4015, 0.0),
 (4014, 0.025717224993681984),
 (4013, 0.041666666666666664),
 (4012, 0.0),
 (4011, 0.16666666666666666),
 (4010, 0.029462782549439476),
 (4009, 0.0),
 (4008, 0.0),
 (4007, 0.07647191129018724),
 (4006, 0.0),
 (4005, 0.023809523809523808),
 (4004, 0.0),
 (4003, 0.018633899812498245),
 (4002, 0.0),
 (4001, 0.11470786693528086),
 (4000, 0.14213381090374028),
 (3999, 0.0),
 (3998, 0.024310831916315757),
 (3997, 0.0),
 (3996, 0.03268602252303067),
 (3995, 0.07647191129018724),
 (3994, 0.0200643088476282),
 (3993, 0.050251890762960605),
 (3992, 0.025717224993681984),
 (3991, 0.025416428388767443),
 (3990, 0.0),
 (3989, 0.0445435403187374),
 (3988, 0.03268602252303067),
 (3987, 0.0),
 (3986, 0.0),
 (3985, 0.0),
 (3984, 0.03333333333333333),
 (3983, 0.07647191129018724),
 (3982, 0.015474611514754322),
 (3981, 0.0),
 (3980, 0.03726779962499649),
 (3979, 0.046225016352102424),
 (3978, 0.03333333333333333),
 (3977, 0.07273929674533079),
 (3976, 0.0),
 (3975, 0.0),
 (3974, 0.0),
 (3973, 0.03823595564509362),
 (3972, 0.03726779962499649),
 (3971, 0.0),
 (3970, 0.0),
 (3969, 0.03333333333333333),
 (3968, 0.0),
 (3967, 0.0),
 (3966, 0.0),
 (3965, 0.0),
 (3964, 0.023112508176051212),
 (3963, 0.043033148291193514),
 (3962, 0.021166687833365082),
 (3961, 0.0),
 (3960, 0.0),
 (3959, 0.0),
 (3958, 0.0),
 (3957, 0.0314970394174356),
 (3956, 0.04042260417272216),
 (3955, 0.10910894511799618),
 (3954, 0.029462782549439476),
 (3953, 0.0),
 (3952, 0.03367175148507369),
 (3951, 0.023338001400466827),
 (3950, 0.046225016352102424),
 (3949, 0.03726779962499649),
 (3948, 0.022680460581325723),
 (3947, 0.03268602252303067),
 (3946, 0.0),
 (3945, 0.0),
 (3944, 0.0),
 (3943, 0.0),
 (3942, 0.0),
 (3941, 0.0),
 (3940, 0.0),
 (3939, 0.0),
 (3938, 0.049690399499995326),
 (3937, 0.0),
 (3936, 0.05986843400892497),
 (3935, 0.027777777777777776),
 (3934, 0.0),
 (3933, 0.025416428388767443),
 (3932, 0.06950480468569159),
 (3931, 0.026352313834736494),
 (3930, 0.03726779962499649),
 (3929, 0.0),
 (3928, 0.0),
 (3927, 0.06085806194501845),
 (3926, 0.027777777777777776),
 (3925, 0.03268602252303067),
 (3924, 0.050251890762960605),
 (3923, 0.0),
 (3922, 0.04042260417272216),
 (3921, 0.0),
 (3920, 0.0),
 (3919, 0.04042260417272216),
 (3918, 0.0314970394174356),
 (3917, 0.027777777777777776),
 (3916, 0.0),
 (3915, 0.0445435403187374),
 (3914, 0.020998026278290397),
 (3913, 0.027036903521793755),
 (3912, 0.0),
 (3911, 0.08574929257125441),
 (3910, 0.0),
 (3909, 0.0),
 (3908, 0.07808688094430304),
 (3907, 0.0),
 (3906, 0.06350006350009524),
 (3905, 0.02817180849095055),
 (3904, 0.0),
 (3903, 0.0),
 (3902, 0.034752402342845795),
 (3901, 0.034020690871988585),
 (3900, 0.0),
 (3899, 0.0),
 (3898, 0.0),
 (3897, 0.048112522432468816),
 (3896, 0.0),
 (3895, 0.0),
 (3894, 0.0),
 (3893, 0.01950685786602176),
 (3892, 0.03823595564509362),
 (3891, 0.06085806194501845),
 (3890, 0.0),
 (3889, 0.050251890762960605),
 (3888, 0.034020690871988585),
 (3887, 0.0),
 (3886, 0.048112522432468816),
 (3885, 0.0),
 (3884, 0.0),
 (3883, 0.0),
 (3882, 0.048621663832631515),
 (3881, 0.0),
 (3880, 0.024845199749997663),

In [101]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x:x[1])[1:6]    #this will sort the values by 2nd index and give only 5 values ->not including the first values as it is the same movie with similarity 1

[(539, 0.25724787771376323),
 (1194, 0.2545875386086578),
 (507, 0.24948506639458295),
 (260, 0.24759378423606915),
 (1216, 0.24459979523511427)]

In [122]:
recommend('Titanic')                #give movies its working........

(818, 0.2799748199650662)
(1565, 0.26376748066999867)
(310, 0.2565749812494094)
(2149, 0.25407300912308384)
(104, 0.23805588025744623)

In [121]:
def recommend(movie):
    movie_index = new_df[new_df['original_title'] == movie].index[0]
    distances = similarity[movie_index] 
    movie_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_df.iloc[i[0]].original_title)

In [115]:
import pickle

In [116]:
pickle.dump(new_df,open('movies.pkl','wb'))               #as in streamlit we r not able to send the dataframes due some pandas issues

In [117]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))          #so we are converting it to dictionary and then sending it....

In [118]:
pickle.dump(similarity,open('similarity.pkl','wb'))